title:            Catlog
description:      A jekyll theme. Because I scribble.
url:              http://catlog.info
signoff:          # Your name.
disqus_shortname: catlog
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: UA-54358039-1

links:
  - name:         About
    url:          /about
  - name:         Email
    url:          mailto:aiasfina@gmail.com
    external:     true
  - name:         GitHub
    url:          https://github.com/aiasfina
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
