// Generated by CoffeeScript 1.6.3
jQuery(function() {
  $.each($("[data-time]"), function(index, ele) {
    return $(ele).html(prettyDate(new Date($(this).data("time"))));
  });

  $('#main-content').smoothState();
});
